apiVersion: v1
kind: Service
metadata:
  name: fraud-engine-service
  namespace: fraud-engine
  labels:
    app: fraud-engine
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: http  # Important for Prometheus
  selector:
    app: fraud-engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-engine-deployment
  namespace: fraud-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-engine
  template:
    metadata:
      labels:
        app: fraud-engine
    spec:
      containers:
      - name: fraud-engine
        # The pipeline will update this tag automatically
        image: ranjpdocker/fraud-engine:3fc13b2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: DB_DSN
          value: "postgres://admin:admin123@postgres:5432/fraud_db?sslmode=disable"
