apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-redis-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  redis-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Redis-Fraud
        type: redis-datasource
        url: redis.fraud-engine.svc.cluster.local:6379
        access: proxy
        isDefault: false
        jsonData:
          client: standalone
          pingInterval: 60